# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ferremas.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ferremas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65rremas.proto\x12\x08\x66\x65rremas\"\x07\n\x05\x45mpty\"&\n\x0fSucursalRequest\x12\x13\n\x0bsucursal_id\x18\x01 \x01(\x05\"E\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\r\n\x05stock\x18\x04 \x01(\x05\"9\n\x08Sucursal\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x11\n\tdireccion\x18\x03 \x01(\t\":\n\x11ProductosResponse\x12%\n\tproductos\x18\x01 \x03(\x0b\x32\x12.ferremas.Producto\"<\n\x12SucursalesResponse\x12&\n\nsucursales\x18\x01 \x03(\x0b\x32\x12.ferremas.Sucursal2\x9f\x01\n\x0f\x46\x65rremasService\x12I\n\x0fListarProductos\x12\x19.ferremas.SucursalRequest\x1a\x1b.ferremas.ProductosResponse\x12\x41\n\x10ListarSucursales\x12\x0f.ferremas.Empty\x1a\x1c.ferremas.SucursalesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ferremas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_SUCURSALREQUEST']._serialized_start=37
  _globals['_SUCURSALREQUEST']._serialized_end=75
  _globals['_PRODUCTO']._serialized_start=77
  _globals['_PRODUCTO']._serialized_end=146
  _globals['_SUCURSAL']._serialized_start=148
  _globals['_SUCURSAL']._serialized_end=205
  _globals['_PRODUCTOSRESPONSE']._serialized_start=207
  _globals['_PRODUCTOSRESPONSE']._serialized_end=265
  _globals['_SUCURSALESRESPONSE']._serialized_start=267
  _globals['_SUCURSALESRESPONSE']._serialized_end=327
  _globals['_FERREMASSERVICE']._serialized_start=330
  _globals['_FERREMASSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
